#                                                                        #
# Testing settings for the package "Soap"                                #
#                                                                        #

Soap:
  exposeExceptionInformation: yes
  logDetailedExceptions: no
