#                                                                        #
# Default subroutes configuration for the Soap package                   #
#                                                                        #

##
# WSDL

-
  name: 'WSDL'
  uriPattern: '{wsdlUri}'
  defaults:
    '@package':    'TYPO3.Soap'
    '@controller': 'Wsdl'
    '@action':     'show'
  routeParts:
    wsdlUri:
      handler: TYPO3\Soap\Routing\WsdlRoutePartHandler
