#                                                                        #
# Default settings for the package "Soap"                                #
#                                                                        #

TYPO3:

  Flow:
    http:
      chain:
        'process':
          chain:
            'soap':
              position: 'before routing'
              component: 'TYPO3\Soap\Http\SoapComponent'
  Soap:

    wsdlResponseContentType: 'application/wsdl+xml'

    soapResponseContentType: 'text/xml'

    # This path will be prefixed with the current web base URI and be suffixed
    # with the service name.
    #
    # If it does not conflict with any other URI you are using in your application,
    # there's no need to change it.
    endpointUriBasePath: 'service/soap/'

    # Expose the exception information to the client in a SOAP fault. Should
    # not be used in production context.
    exposeExceptionInformation: no

    # Log detailed exception information including a stacktrace of the exception.
    logDetailedExceptions: yes

    # Log debug information about requests
    logRequests: no

    # Default template for WSDL generator
    generatorTemplate: 'resource://TYPO3.Soap/Private/Templates/Definitions.xml'

    # Explicit mapping of object names to URLs and XML namespaces for WSDL generator and SOAP request handler
    #
    # mapping:
    #   Package\SomeObjectName:
    #     path: path/after/endpointUriBasePath
    #     namespace: http://example.com/some/xml/namespace
