#                                                                        #
# Default settings for the package "Soap"                                #
#                                                                        #

Soap:
  # This path will be prefixed with the current web base URI and be suffixed
  # with the service name.
  #
  # If it does not conflict with any other URI you are using in your application,
  # there's no need to change it.
  endpointUriBasePath: 'service/soap/'

