#                                                                        #
# Development settings for the package "Soap"                            #
#                                                                        #

TYPO3:
  Soap:
    exposeExceptionInformation: yes
    logDetailedExceptions: no
    logRequests: no
